GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

local wilson_attack = 34
local wilson_sanity = 200

for k,v in pairs({
    WANDA_OLDAGER = 60, -- 20 to 80 yo
    OLDAGE_HEALTH_SCALE = 60/150, -- WANDA_OLDAGER / WILSON_HEALTH
    WANDA_HUNGER = 175,
    WANDA_SANITY = wilson_sanity,

    WANDA_MIN_YEARS_OLD = 20,
    WANDA_MAX_YEARS_OLD = 80,

    WANDA_AGE_THRESHOLD_OLD = .25,
    WANDA_AGE_THRESHOLD_YOUNG = .75,

    POCKETWATCH_SHADOW_DAMAGE = wilson_attack * 2.4,
    POCKETWATCH_DEPLETED_DAMAGE = wilson_attack * .8,

    POCKETWATCH_HEAL_COOLDOWN = TUNING.SEG_TIME * 4,
    POCKETWATCH_HEAL_HEALING = 20, -- health pre-oldager modifier

    POCKETWATCH_WARP_COOLDOWN = 2,
    POCKETWATCH_RECALL_COOLDOWN = TUNING.TOTAL_DAY_TIME,

    WANDA_OLD_HAMMER_EFFECTIVENESS = 0.75,
    LONGEST_ACTION_TIMEOUT = 1.5,

    WANDA_STAFFSANITY_YOUNG = 1,
    WANDA_STAFFSANITY_NORMAL = 0.5,
    WANDA_STAFFSANITY_OLD = 0.25,

    WANDA_SHADOW_RESISTANCE_YOUNG = 1,
    WANDA_SHADOW_RESISTANCE_NORMAL = 0.33,
    WANDA_SHADOW_RESISTANCE_OLD = 0,

    WANDA_REGULAR_DAMAGE_OLD = 0.5,
    WANDA_REGULAR_DAMAGE_NORMAL = 1,
    WANDA_REGULAR_DAMAGE_YOUNG = 1,

    WANDA_SHADOW_DAMAGE_OLD = 1.75,
    WANDA_SHADOW_DAMAGE_NORMAL = 1.2,
    WANDA_SHADOW_DAMAGE_YOUNG = 1,

    WANDA_WARP_DIST_OLD = 2,
    WANDA_WARP_DIST_NORMAL = 4,
    WANDA_WARP_DIST_YOUNG = 8,

    WHIP_RANGE = 2,
    
    -- food affinity multipliers to add 15 calories
    AFFINITY_15_CALORIES_TINY = 2.6,
    AFFINITY_15_CALORIES_SMALL = 2.2,
    AFFINITY_15_CALORIES_MED = 1.6,
    AFFINITY_15_CALORIES_LARGE = 1.4,
    AFFINITY_15_CALORIES_HUGE = 1.2,
    AFFINITY_15_CALORIES_SUPERHUGE = 1.1,
})
do
    TUNING[k] = v
end
